language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  include:
    - php: 5.6
      env: COMPOSER_EXTRA_ARGS="--prefer-lowest --prefer-stable"

before_install:
  - composer self-update

install:
  - travis_retry composer update --no-interaction --prefer-dist $COMPOSER_EXTRA_ARGS
  - travis_retry composer create-project --prefer-source --no-interaction jakub-onderka/php-parallel-lint /tmp/php-parallel-lint ~0.9
  - travis_retry composer create-project nette/code-checker /tmp/code-checker ~2.5 --no-interaction
  - which redis-server
  - cat /etc/redis/redis.conf
  - tests/travis.redis.sh
  - tests/travis.phpredis.sh

before_script:
  - redis-cli info |grep version

script:
  - vendor/bin/tester -p php -c ./tests/php.ini-unix ./tests/KdybyTests/
  - php /tmp/php-parallel-lint/parallel-lint.php -e php,phpt --exclude vendor .
  - php /tmp/code-checker/src/code-checker.php

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'

cache:
    directories:
        - $HOME/.composer/cache
